from __future__ import annotations

from typing import Any

ANALOG_FRIENDLY_NAMES: dict[int, str] = {
    0: "Kesseltemperatur Ist",
    1: "Rauchgastemperatur Ist",
    2: "Sauerstoff O2 Ist",
    3: "Puffer oben",
    4: "Puffer Mitte",
    5: "Puffer unten",
    6: "Außentemperatur",
    7: "Heizkreis 1 Vorlauf Ist",
    8: "Heizkreis 2 Vorlauf Ist",
    9: "Heizkreis 1 Raumtemperatur Ist",
    10: "Heizkreis 2 Raumtemperatur Ist",
    11: "Boiler 1 Temperatur Ist",
    12: "Heizkreis 1 Vorlauf Soll",
    13: "Heizkreis 2 Vorlauf Soll",
    14: "Heizkreis 1 Raumtemperatur Soll",
    15: "Heizkreis 2 Raumtemperatur Soll",
    16: "Primärluftklappe Ist",
    17: "Primärluftklappe Soll",
    18: "Sekundärluftklappe Ist",
    19: "Sekundärluftklappe Soll",
    20: "Saugzug Soll",
    21: "Rücklaufpumpe Leistung",
    22: "Kesselzustand Code",
    23: "Sauerstoff O2 Soll",
    24: "Lambda-Sondenspannung",
    25: "Rauchgastemperatur Soll",
    26: "Kesselleistung",
    27: "Kesseltemperatur Soll",
    28: "Heizkreis 3 Vorlauf Ist",
    29: "Heizkreis 4 Vorlauf Ist",
    30: "Heizkreis 3 Raumtemperatur Ist",
    31: "Heizkreis 4 Raumtemperatur Ist",
    32: "Boiler 2 Temperatur Ist",
    33: "Heizkreis 3 Vorlauf Soll",
    34: "Heizkreis 4 Vorlauf Soll",
    35: "Heizkreis 3 Raumtemperatur Soll",
    36: "Heizkreis 4 Raumtemperatur Soll",
    37: "Heizkreis 5 Vorlauf Ist",
    38: "Heizkreis 6 Vorlauf Ist",
    39: "Heizkreis 5 Raumtemperatur Ist",
    40: "Heizkreis 6 Raumtemperatur Ist",
    41: "Boiler 3 Temperatur Ist",
    42: "Heizkreis 5 Vorlauf Soll",
    43: "Heizkreis 6 Vorlauf Soll",
    44: "Heizkreis 5 Raumtemperatur Soll",
    45: "Heizkreis 6 Raumtemperatur Soll",
    46: "Saugzug Ist",
    47: "Platinentemperatur",
    48: "Rücklauftemperatur Ist",
    49: "Puffer Ladezustand",
    50: "Anforderung Heizkreis A",
    51: "Anforderung Heizkreis 1",
    52: "Anforderung Heizkreis 2",
    53: "Fremdwärme Temperatur",
    54: "Rücklauftemperatur Soll",
    55: "Außentemperatur gemittelt",
    56: "Boiler A Temperatur Ist",
    57: "Heizkreis A Vorlauf Soll",
    58: "Heizkreis A Raumtemperatur Soll",
    59: "Heizkreis A Raumtemperatur Ist",
    60: "Heizkreis A Vorlauf Ist",
    61: "Fernbedienung A Zustand",
    62: "Fernbedienung 1 Zustand",
    63: "Fernbedienung 2 Zustand",
    64: "Fernbedienung 3 Zustand",
    65: "Fernbedienung 4 Zustand",
    66: "Fernbedienung 5 Zustand",
    67: "Fernbedienung 6 Zustand",
    68: "Raumtemperatur A",
    69: "Raumtemperatur 1",
    70: "Raumtemperatur 2",
    71: "Raumtemperatur 3",
    72: "Raumtemperatur 4",
    73: "Raumtemperatur 5",
    74: "Raumtemperatur 6",
    75: "Pelletkessel Temperatur Ist",
    76: "Pelletkessel Zustand Code",
    77: "Pelletkessel O2 Ist",
    78: "Pelletkessel O2 Soll",
    79: "Anforderung Heizkreis 3",
    80: "Pelletkessel Temperatur Soll",
    81: "Pelletkessel Rauchgastemperatur",
    82: "Pelletkessel Rücklauf Ist",
    83: "Pelletkessel Rücklauf Soll",
    84: "Pelletkessel Rücklaufpumpe Leistung",
    85: "Pelletkessel Platinentemperatur",
    86: "Pelletkessel Saugzug Soll",
    87: "Pelletkessel Saugzug Ist",
    88: "Pelletkessel Brennstoff Skala",
    89: "Pelletkessel Einschub Regler",
    90: "Pelletkessel Einschub Soll",
    91: "Pelletkessel Einschub Strom",
    92: "Pelletkessel Rostantrieb Strom",
    93: "Pelletkessel Ascheaustragung Strom",
    94: "Pelletkessel Saugrost Strom",
    95: "Anforderung Heizkreis 9",
    96: "Pelletkessel Lambda-Sondenspannung",
    97: "Anforderung Heizkreis 4",
    98: "Anforderung Heizkreis 5",
    99: "Anforderung Heizkreis 6",
    100: "Anforderung Heizkreis 7",
    101: "Pelletkessel Saugrost Motor",
    102: "Pelletkessel Saugrost Position Ist",
    103: "Pelletkessel Saugrost Modus",
    104: "Pelletkessel Einschub Position aktiv",
    105: "Pelletkessel Einschub Motor Soll",
    106: "Pelletkessel Einschub Motor Ist",
    107: "Pelletkessel Verbrauchszähler",
    108: "Pelletkessel Laufzeit Einschub seit Entleerung",
    109: "Pelletkessel Laufzeit Einschub seit Füllung",
    110: "Pelletkessel Lagerstand",
    111: "Pelletkessel Leistung",
    112: "Pelletkessel Lambda-Heizung Strom",
    113: "Pelletkessel Lambda-Heizung Spannung",
    114: "Anforderung Heizkreis 8",
    115: "Fremdwärme Anforderung",
    116: "Verbraucher Anforderung",
    117: "Heizkreis A Zustand Code",
    118: "Heizkreis 1 Zustand Code",
    119: "Heizkreis 2 Zustand Code",
    120: "Heizkreis 3 Zustand Code",
    121: "Heizkreis 4 Zustand Code",
    122: "Heizkreis 5 Zustand Code",
    123: "Heizkreis 6 Zustand Code",
    124: "Boiler A Zustand Code",
    125: "Boiler 1 Zustand Code",
    126: "Boiler 2 Zustand Code",
    127: "Boiler 3 Zustand Code",
    128: "Gesamtvorlauf Temperatur",
    129: "Pelletkessel Einschub Sollposition",
    130: "Pelletkessel Einschub Istposition",
    131: "Pelletkessel Einschub Strom",
    132: "Anforderung Heizkreis 10",
    133: "Anforderung Heizkreis 11",
    134: "Anforderung Heizkreis 12",
    135: "Anforderung Heizkreis 13",
    136: "Anforderung Heizkreis 14",
    137: "Anforderung Heizkreis 15",
    138: "BLDC Einschub Soll-Drehzahl",
    139: "BLDC Einschub Ist-Drehzahl",
    140: "Lambda-Heizung Leistung",
    141: "Störungsnummer",
    142: "Differenzregelung Sensor 1",
    143: "Differenzregelung Sensor 2",
    144: "Spültemperatur",
    145: "Puffer Mitte oben",
    146: "Puffer Mitte unten",
    147: "Lambda-Heizung Spannung",
    148: "Lambda-Heizung Strom",
    149: "Differenzregelung 2 Sensor 3",
    150: "Differenzregelung 2 Sensor 4",
    151: "Boiler B Temperatur Ist",
    152: "Boiler B Temperatur Soll",
    153: "Boiler B Zustand Code",
    154: "Heizkreis B Vorlauf Ist",
    155: "Heizkreis B Vorlauf Soll",
    156: "Heizkreis B Raumtemperatur Ist",
    157: "Heizkreis B Raumtemperatur Soll",
    158: "Heizkreis B Zustand Code",
    159: "Raumtemperatur B",
    160: "Fernbedienung B Zustand",
    161: "Pelletkessel Lambda-Heizung Leistung",
}

DIGITAL_FRIENDLY_NAMES: dict[str, str] = {
    "d00_01_hkp1": "Heizkreis 1 Pumpe",
    "d00_02_hkp2": "Heizkreis 2 Pumpe",
    "d00_03_m1a": "Heizkreis 1 Mischer öffnet",
    "d00_04_m1z": "Heizkreis 1 Mischer schließt",
    "d00_05_m2a": "Heizkreis 2 Mischer öffnet",
    "d00_06_m2z": "Heizkreis 2 Mischer schließt",
    "d00_07_boilanf_1": "Boiler 1 Anforderung",
    "d00_08_lamdaheiz": "Lambda-Heizung",
    "d00_10_z_ndheiz": "Zündheizung",
    "d00_11_slk_auf": "Sekundärluftklappe öffnet",
    "d00_12_slk_zu": "Sekundärluftklappe schließt",
    "d00_13_plk_auf": "Primärluftklappe öffnet",
    "d00_14_plk_zu": "Primärluftklappe schließt",
    "d01_00_stb": "Sicherheitstemperaturbegrenzer",
    "d01_01_tks": "Kesseltemperatur Sicherheit",
    "d01_02_st_rung": "Störung",
    "d01_03_ext_anf": "Externe Anforderung",
    "d02_00_bp1": "Boiler 1 Pumpe",
    "d02_01_bp2": "Boiler 2 Pumpe",
    "d02_02_bp3": "Boiler 3 Pumpe",
    "d02_03_rlm_auf": "Rücklaufmischer öffnet",
    "d02_04_rlm_zu": "Rücklaufmischer schließt",
    "d02_05_schnellladev": "Schnellladeventil",
    "d03_00_hkp3": "Heizkreis 3 Pumpe",
    "d03_01_hkp4": "Heizkreis 4 Pumpe",
    "d03_03_m3a": "Heizkreis 3 Mischer öffnet",
    "d03_04_m3z": "Heizkreis 3 Mischer schließt",
    "d03_05_m4a": "Heizkreis 4 Mischer öffnet",
    "d03_06_m4z": "Heizkreis 4 Mischer schließt",
    "d03_07_boilanf_2": "Boiler 2 Anforderung",
    "d03_08_zp_boi_1": "Boiler 1 Zirkulationspumpe",
    "d03_09_zp_boi_2": "Boiler 2 Zirkulationspumpe",
    "d03_10_zp_boi_3": "Boiler 3 Zirkulationspumpe",
    "d04_00_hkp5": "Heizkreis 5 Pumpe",
    "d04_01_hkp6": "Heizkreis 6 Pumpe",
    "d04_03_m5a": "Heizkreis 5 Mischer öffnet",
    "d04_04_m5z": "Heizkreis 5 Mischer schließt",
    "d04_05_m6a": "Heizkreis 6 Mischer öffnet",
    "d04_06_m6z": "Heizkreis 6 Mischer schließt",
    "d04_07_boilanf_3": "Boiler 3 Anforderung",
    "d04_11_fw_freig": "Fremdwärme Freigabe",
    "d04_12_fw_pumpe": "Fremdwärme Pumpe",
    "d04_13_flp": "Fernleitungspumpe",
    "d04_14_pk_lambdaok": "Pelletkessel Lambda OK",
    "d05_00_hkpa": "Heizkreis A Pumpe",
    "d05_01_maa": "Heizkreis A Mischer öffnet",
    "d05_02_maz": "Heizkreis A Mischer schließt",
    "d05_03_bpa": "Boiler A Pumpe",
    "d05_04_zp_boi_a": "Boiler A Zirkulationspumpe",
    "d05_05_boilanf_a": "Boiler A Anforderung",
    "d05_06_pk_fuellstand": "Pelletkessel Füllstand",
    "d05_07_hkpb": "Heizkreis B Pumpe",
    "d05_08_mba": "Heizkreis B Mischer öffnet",
    "d05_09_mbz": "Heizkreis B Mischer schließt",
    "d05_10_bpb": "Boiler B Pumpe",
    "d05_11_zp_boi_b": "Boiler B Zirkulationspumpe",
    "d05_12_boilanf_b": "Boiler B Anforderung",
    "d05_14_pk_aa_run": "Pelletkessel Ascheaustragung läuft",
    "d05_15_pk_aa_dir": "Pelletkessel Ascheaustragung Richtung",
    "d06_00_pk_l_heiz": "Pelletkessel Lambda-Heizung",
    "d06_01_pk_z_heiz": "Pelletkessel Zündheizung",
    "d06_02_pk_z_geb": "Pelletkessel Zündgebläse",
    "d06_04_pk_aschebox": "Pelletkessel Aschebox",
    "d06_05_pk_es_run": "Pelletkessel Einschub läuft",
    "d06_06_pk_es_dir": "Pelletkessel Einschub Richtung",
    "d06_07_pk_as_saug": "Pelletkessel Aschesauger",
    "d06_08_pk_as_ra_run": "Pelletkessel Raumaustragung läuft",
    "d06_09_pk_as_ra_dir": "Pelletkessel Raumaustragung Richtung",
    "d06_10_pk_rein_en": "Pelletkessel Reinigung Freigabe",
    "d06_11_pk_rein_run": "Pelletkessel Reinigung läuft",
    "d06_12_pk_rlm_auf": "Pelletkessel Rücklaufmischer öffnet",
    "d06_13_pk_rlm_zu": "Pelletkessel Rücklaufmischer schließt",
    "d06_14_pk_rl_pumpe": "Pelletkessel Rücklaufpumpe",
    "d06_15_pk_rl_verz_aktiv": "Pelletkessel Rücklaufverzögerung aktiv",
    "d07_00_gflp": "Gesamt-Fernleitungspumpe",
    "d07_01_gflm_auf": "Gesamt-Fernleitungsmischer öffnet",
    "d07_02_gflm_zu": "Gesamt-Fernleitungsmischer schließt",
    "d07_03_dreg_p1": "Differenzregelung Pumpe 1",
    "d07_04_dreg_p2": "Differenzregelung Pumpe 2",
    "d07_05_dreg_mi_auf": "Differenzregelung Mischer öffnet",
    "d07_06_dreg_mi_zu": "Differenzregelung Mischer schließt",
    "d07_07_sp_lung_aktiv": "Spülung aktiv",
    "d07_08_dreg2_p1": "Differenzregelung 2 Pumpe 1",
    "d07_09_dreg2_p2": "Differenzregelung 2 Pumpe 2",
    "d07_10_dreg2_mi_auf": "Differenzregelung 2 Mischer öffnet",
    "d07_11_dreg2_mi_zu": "Differenzregelung 2 Mischer schließt",
}


def friendly_analog_name(channel: dict[str, Any]) -> str:
    return ANALOG_FRIENDLY_NAMES.get(channel["id"], channel["name"])


def friendly_digital_name(channel: dict[str, Any]) -> str:
    return DIGITAL_FRIENDLY_NAMES.get(channel["key"], channel["name"])
